# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa82b7542a7c7882536a95fa30436f2a0b719c7fa98428bc2ad5a5a3ba63b3e5787929e7febc26d5a65567bd8a7cc0f702543e1adebc9210eac80a3bec4faa3

test:
  secret_key_base: 6b52b476a70079280de467f7f6eab9eba5de6e8b5ee06ab157071fc0d71c811e81a2c1835ce3eb7a8139cc48cf47d78cd2b4a2209524394307e1d64b481dcd4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
